//ENTRY(ID,  var,                  rightshift,  resolution,    unit,    name,                      minvalue,   maxvalue  )

ENTRY('1', controlPara.angleBySpeed,         0,    1.0,           "",    "angleBySpeed",           -50.0,      50.0      )
ENTRY('2', controlPara.angleByPosition,      0,    1.0,           "",    "angleByPosition",        -50.0,      50.0      )
ENTRY('3', controlPara.powerByAngleDiv,      0,    1.0,           "",    "powerByAngleDiv",        -50.0,      50.0      )
ENTRY('4', controlPara.powerByAngleRateDiv,  0,    1.0,           "",    "powerByAngleRateDiv",    -50.0,      50.0      )

ENTRY(0,   lastLoopTicks,                    0,    0.0,           "-",   "Ende der Tabelle",        0.0,        0.0      )
